# Generated by Django 4.2.6 on 2024-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="name",
            field=models.CharField(
                default="", max_length=12, verbose_name="Имя курьера"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("1", "Обрабатывается"),
                    ("2", "Подготавливают"),
                    ("3", "Готов"),
                ],
                max_length=255,
                verbose_name="Состояние",
            ),
        ),
    ]
