# Generated by Django 4.2.6 on 2024-02-05 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0002_alter_order_deliverto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="deliverTo",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2024, 2, 5, 13, 49, 53, 911152),
                verbose_name="Доставить до",
            ),
        ),
    ]
