# Generated by Django 4.2.6 on 2024-01-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0002_courier_name_alter_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="courier",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diplom.courier",
                verbose_name="Курьер",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="vendor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="diplom.vendor",
                verbose_name="Заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="review",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
