# Generated by Django 4.2.6 on 2024-01-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0003_alter_customuser_courier_alter_customuser_vendor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="number",
            field=models.CharField(
                max_length=17, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
