# Generated by Django 4.2.6 on 2024-02-03 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0004_alter_courier_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="IDCourier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Курьер",
            ),
        ),
    ]
