# Generated by Django 4.2.6 on 2024-02-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("diplom", "0005_alter_order_idcourier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="IDVendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="diplom.vendor",
                verbose_name="Заказчик",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата и время создания"
            ),
        ),
    ]
